<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/lv/default.php 
 * 
 * Contao extension: taxonomy 0.1.8 stable 
 * Latvian translation file 
 * 
 * Copyright : &copy; 2008-2011 Thyon Design, Martin Komara, CyberSpectrum 
 * License   : LGPL 
 * Author    : Christian Schiffler (Xtra), http://www.cyberspectrum.de 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['taxonomyTree'] = "Taksonomijas noteikumi";
 
?>
