<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/lv/tl_taxonomy.php 
 * 
 * Contao extension: taxonomy 0.1.8 stable 
 * Latvian translation file 
 * 
 * Copyright : &copy; 2008-2011 Thyon Design, Martin Komara, CyberSpectrum 
 * License   : LGPL 
 * Author    : Christian Schiffler (Xtra), http://www.cyberspectrum.de 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Taksonomijas noteikumi";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Nosaukums";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Ierakstiet taksonomijas noteikumu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Aizstājējvārds";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Jauns noteikums";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Izveidot jaunu noteikumu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Noteikuma detaļas";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Parādīt noteikuma ID %s detaļas.";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Rediģēt noteikumu";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Rediģēt ID %s noteikumu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Duplicēt noteikumu";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Duplicēt ID %s noteikumu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['0'] = "Pārvietot noteikumu";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['1'] = "Pārvietot ID %s noteikumu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Dzēst noteikumu";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Dzēst ID %s noteikumu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['0'] = "Duplicēt noteikumu ar apapkšnoteikumiem";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['1'] = "Duplicēt ID %s noteikumu ar apapkšnoteikumiem";
$GLOBALS['TL_LANG']['tl_taxonomy']['title_legend'] = "Nosaukums un aizstājējvārds";
 
?>
