<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/cs/modules.php 
 * 
 * Contao extension: taxonomy 0.1.7 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008-2010 Thyon Design, Martin Komara 
 * License   : LGPL 
 * Author    : Christian Schiffler (Xtra), http://www.cyberspectrum.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['taxonomy']['0'] = "Taxonomie";
$GLOBALS['TL_LANG']['MOD']['taxonomy']['1'] = "Tento modul umožňuje spravovat sbírku taxonomie podmínek (nebo tagů).";
 
?>
