<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/cs/tl_taxonomy.php 
 * 
 * Contao extension: taxonomy 0.1.7 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008-2010 Thyon Design, Martin Komara 
 * License   : LGPL 
 * Author    : Christian Schiffler (Xtra), http://www.cyberspectrum.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Taxonomie podmínky";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Jméno";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Zadejte název taxonomie podmínky.";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['1'] = "Alias je použit pro odkazování podmínek, zpravidla v URL filtrech.";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Nová podmínka";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Vytvořit novou podmínku";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Podrobnosti podmínky";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Zobrazit podrobnosti o podmínce ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Upravit podmínku";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Upravit podmínku ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Duplikovat podmínku";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Duplikovat podmínku ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['0'] = "Přesunout podmínku";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['1'] = "Přesunout podmínku ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Vymazat podmínku";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Vymazat podmínku ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['0'] = "Duplikovat podmínku s sub-podmínkami";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['1'] = "Duplikovat podmínku ID %s s sub-podmínkami";
$GLOBALS['TL_LANG']['tl_taxonomy']['title_legend'] = "Název a alias";
 
?>
