<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/cs/tl_user.php 
 * 
 * Contao extension: taxonomy 0.1.7 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008-2010 Thyon Design, Martin Komara 
 * License   : LGPL 
 * Author    : Christian Schiffler (Xtra), http://www.cyberspectrum.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['taxonomymounts']['0'] = "Taxonomievrchol";
$GLOBALS['TL_LANG']['tl_user']['taxonomymounts']['1'] = "Prosím, vyberte taxonomie root kořeny které chcete povolit pro aktuálního uživatele. Sub kořeny budou zařazeny automaticky.";
$GLOBALS['TL_LANG']['tl_user']['taxonomytitle'] = "Taxonomie Strom";
$GLOBALS['TL_LANG']['tl_user']['taxonomy_legend'] = "Taxonomie vrchol";
 
?>
