<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/nl/modules.php 
 * 
 * TYPOlight extension: taxonomy 0.1.5 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['taxonomy']['0'] = "Taxonomie";
$GLOBALS['TL_LANG']['MOD']['taxonomy']['1'] = "Deze module wordt gebruikt om hiërarchieën van begrippen (classificaties) te maken.";
 
?>
