<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/nl/tl_taxonomy.php 
 * 
 * TYPOlight extension: taxonomy 0.1.5 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Taxonomische begrippen";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Naam";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Naam begrip.";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['1'] = "Alias die naar het begrip verwijst.";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Nieuw begrip";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Maak een nieuw begrip.";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Bewerk begrip";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Bewerk begrip ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Kopieer begrip";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Kopieer begrip ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Wis begrip";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Wis begrip ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Begrip details";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Toon details van begrip ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['editheader']['0'] = "Bewerk begrip";
$GLOBALS['TL_LANG']['tl_taxonomy']['editheader']['1'] = "Bewerk het begrip.";
 
?>
