<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/it/default.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['taxonomyTree'] = "Termini tassonomia";
 
?>
