<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/it/tl_taxonomy.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Termini tassonomia";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Nome";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Nome del termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['1'] = "Alias utilizzato per riferirsi al termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Nuovo termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Crea un nuovo termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Dettagli termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Visualizza i dettagli del termine ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Modifica termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Modifica termine ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Copia termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Copia termine ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['0'] = "Sposta termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['1'] = "Sposta termine ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Elimina termine";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Elimina termine ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['0'] = "Duplica termine e sottotermini";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['1'] = "Duplica termine ID %s e sottotermini";
 
?>
