<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/ru/modules.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['taxonomy']['0'] = "Таксономия";
$GLOBALS['TL_LANG']['MOD']['taxonomy']['1'] = "Модуль позволит вам управлять коллекцией терминов таксономии. (или тегов)";
 
?>
