<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/ru/tl_taxonomy.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Термины таксономии";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Имя";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Имя термина";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Алиас";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['1'] = "Алиас является уникальной ссылкой на термин, которую можно вызывать взамен ID термина.";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Новый термин";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Создать новый термин";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Детали термина";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Показать детали термина ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Редактировать термин";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Редактировать термин ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Копировать термин";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Копировать термин ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['0'] = "Перенести термин";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['1'] = "Перенести термин ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Удалить термин";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Удалить термин ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['0'] = "Копировать термин и все вложенные термины";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['1'] = "Копировать термин ID %s и все вложенные термины";
 
?>
