<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/pl/tl_taxonomy.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * Polish translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Terminy taksonomii";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Nazwa";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Naza terminu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['1'] = "Alias będzie użyty jako odnośnik do terminu.";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Nowy termin";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Utwórz nowy termin";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Szczegóły terminu";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Pokaż szczegóły terminu ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Edytuj termin";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Edytuj termin ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Duplikuj termin";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Duplikuj termin ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['0'] = "Przenieś termin";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['1'] = "Przenieś termin ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Usuń termin";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Usuń termin ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['0'] = "Duplikuj termin z podterminami";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['1'] = "Duplikuj termin ID %s z podterminami";
 
?>
