<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/de/modules.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['taxonomy']['0'] = "Taxonomie";
$GLOBALS['TL_LANG']['MOD']['taxonomy']['1'] = "Dieses Modul erlaubt Ihnen, eine Aufstellung von Taxonomie-Bedingungen zu verwalten.";
 
?>
