<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/fr/modules.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['taxonomy']['0'] = "Classification";
$GLOBALS['TL_LANG']['MOD']['taxonomy']['1'] = "Ce module permet de gérer des classification de termes (taxonomie), ex : \"Couleur => noir, blanc, rouge...\", \"Forme => carré, rectangle, triangle...\"";
 
?>
