<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/fr/tl_taxonomy.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Classification de termes";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Nom";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Nom du terme.";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['1'] = "L'alias sera utilisé pour référencer un terme.";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Nouveau terme";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Créer un nouveau terme";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Afficher les détails";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Afficher les détails du terme ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Editer ce terme";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Editer le terme ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Copier ce terme";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Copier le terme ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['0'] = "Déplacer le term";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['1'] = "Déplacer le terme ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Supprimer ce terme";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Supprimer le terme ID %s";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['0'] = "Duppliquer le terme avec ses sous-termes";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['1'] = "Duppliquer le terme ID %s avec ses sous-termes";
 
?>
